name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable # Use stable Rust toolchain
          profile: minimal # Install minimal Rust toolchain

      # Install protoc for protobufs
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
        env:
          DEBIAN_FRONTEND: noninteractive

      # Build the project
      - name: Build project
        run: cargo build --verbose

      # Run tests
      - name: Run tests
        run: RUST_LOG=info cargo test  -- --test-threads=1 --nocapture

